### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by Betoniara** [PiotrMachowski/Home-Assistant-picture-elements-Xiaomi-Vacuum-black#2]
Mógłbyś dodać ta kartę do oficjalnego repozytorium HACS?

**Comment by PiotrMachowski** [comment]
To jest karta typu [picture-elements](https://www.home-assistant.io/lovelace/picture-elements/), nie są one wspierane przez HACS. Trzeba zdefiniować je samemu w konfiguracji interfejsu
