### ISSUE TITLE
Tłumaczenia

### ISSUE THREAD

**Issue by Betoniara** [PiotrMachowski/Home-Assistant-picture-elements-Xiaomi-Vacuum-black#3]
Gdzie można poprawić te tłumaczenia
![en](https://user-images.githubusercontent.com/3316095/65411660-b24eb100-dded-11e9-96fd-55fd0f61f03d.JPG)
![pl](https://user-images.githubusercontent.com/3316095/65411661-b24eb100-dded-11e9-8641-5f6f82ad595a.JPG)

**Comment by PiotrMachowski** [comment]
Te translacje to część samego Home Assistanta, a nie karty, także muszą zostać naprawione w HA.
